package com.binance4j.margin.param;

import com.binance4j.core.annotation.Mandatory;
import com.binance4j.core.annotation.Param;
import com.binance4j.core.dto.RateLimitType;
import com.binance4j.core.param.Params;
import com.binance4j.margin.client.MarginClient;

/**
 * {@link MarginClient#cancelOCO} params.
 * 
 * @param symbol            The related symbol.
 * @param orderListId       Either {@code orderListId} or {@code listClientOrderId} must be provided.
 * @param listClientOrderId Either {@code orderListId} or {@code listClientOrderId} must be provided.
 * @param isIsolated        Is the order isolated?
 * @param newClientOrderId  Used to uniquely identify this cancel. Automatically generated by default.
 */
@Param(type = RateLimitType.UID)
public record CancelOCOParams(@Mandatory String symbol, Long orderListId, String listClientOrderId, Boolean isIsolated, String newClientOrderId)
		implements Params {
	/**
	 * Creates an instance of {@link CancelOCOParams}.
	 * 
	 * @param symbol The related symbol.
	 */
	public CancelOCOParams(String symbol) {
		this(symbol, null, null, false, null);
	}

	/**
	 * Creates an instance of {@link CancelOCOParams}.
	 * 
	 * @param symbol      The related symbol.
	 * @param orderListId The order list id.
	 */
	public CancelOCOParams(String symbol, Long orderListId) {
		this(symbol, orderListId, null, false, null);
	}

	/**
	 * Creates an instance of {@link CancelOCOParams}.
	 * 
	 * @param symbol           The related symbol.
	 * @param orderListId      The order list id.
	 * @param newClientOrderId Used to uniquely identify this cancel. Automatically generated by default.
	 */
	public CancelOCOParams(String symbol, Long orderListId, String newClientOrderId) {
		this(symbol, orderListId, null, false, newClientOrderId);
	}

	/**
	 * Creates an instance of {@link CancelOCOParams}.
	 * 
	 * @param symbol           The related symbol.
	 * @param orderListId      The order list id.
	 * @param isIsolated       Is the order isolated?
	 * @param newClientOrderId Used to uniquely identify this cancel. Automatically generated by default.
	 */
	public CancelOCOParams(String symbol, Long orderListId, Boolean isIsolated, String newClientOrderId) {
		this(symbol, orderListId, null, isIsolated, newClientOrderId);
	}

	/**
	 * Creates an instance of {@link CancelOCOParams}.
	 * 
	 * @param symbol            The related symbol.
	 * @param listClientOrderId The list client order id.
	 */
	public CancelOCOParams(String symbol, String listClientOrderId) {
		this(symbol, null, listClientOrderId, false, null);
	}

	/**
	 * Creates an instance of {@link CancelOCOParams}.
	 * 
	 * @param symbol            The related symbol.
	 * @param listClientOrderId The list client order id.
	 * @param newClientOrderId  Used to uniquely identify this cancel. Automatically generated by default.
	 */
	public CancelOCOParams(String symbol, String listClientOrderId, String newClientOrderId) {
		this(symbol, null, listClientOrderId, false, newClientOrderId);
	}

	/**
	 * Creates an instance of {@link CancelOCOParams}.
	 * 
	 * @param symbol            The related symbol.
	 * @param listClientOrderId The list client order id.
	 * @param isIsolated        Is the order isolated?
	 * @param newClientOrderId  Used to uniquely identify this cancel. Automatically generated by default.
	 */
	public CancelOCOParams(String symbol, String listClientOrderId, Boolean isIsolated, String newClientOrderId) {
		this(symbol, null, listClientOrderId, isIsolated, newClientOrderId);
	}
}