name: deploy

on:
  push:
    branches: 
     - documentation

env:
  FETCH_DEPTH: 0
  JAVA_VERSION: 17
  JAVA_DISTRIBUTION: 'adopt'
  BINANCE_API_KEY: ${{ secrets.BINANCE_API_KEY }}
  BINANCE_API_SECRET: ${{ secrets.BINANCE_API_SECRET }}
  BINANCE_TESTNET_API_KEY: ${{ secrets.BINANCE_TESTNET_API_KEY }}
  BINANCE_TESTNET_API_SECRET: ${{ secrets.BINANCE_TESTNET_API_SECRET }}
  GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
  PASSPHRASE: ${{ secrets.PASSPHRASE }}
  OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
  OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SERVERS: '[{  "id": "ossrh",  "username": "${{ secrets.OSSRH_USERNAME }}",   "password": "${{ secrets.OSSRH_PASSWORD }}"}]'
  BLVT_INSTALLATION: cd binance4j-blvt && mvn install -DskipTests=true 
  C2C_INSTALLATION: cd binance4j-c2c && mvn install -DskipTests=true 
  CONVERT_INSTALLATION: cd binance4j-convert && mvn install -DskipTests=true 
  CORE_INSTALLATION: cd binance4j-core && mvn install -DskipTests=true 
  FIAT_INSTALLATION: cd binance4j-fiat && mvn install -DskipTests=true 
  LOAN_INSTALLATION: cd binance4j-loan && mvn install -DskipTests=true 
  MARGIN_INSTALLATION: cd binance4j-margin && mvn install -DskipTests=true 
  MARKET_INSTALLATION: cd binance4j-market && mvn install -DskipTests=true 
  MINING_INSTALLATION: cd binance4j-mining && mvn install -DskipTests=true 
  NFT_INSTALLATION: cd binance4j-nft && mvn install -DskipTests=true 
  PAY_INSTALLATION: cd binance4j-pay && mvn install -DskipTests=true 
  PORTFOLIO_MARGIN_INSTALLATION: cd binance4j-portfolio-margin && mvn install -DskipTests=true 
  REBATE_INSTALLATION: cd binance4j-rebate && mvn install -DskipTests=true 
  SAVINGS_INSTALLATION: cd binance4j-savings && mvn install -DskipTests=true 
  SPOT_INSTALLATION: cd binance4j-spot && mvn install -DskipTests=true 
  STAKING_INSTALLATION: cd binance4j-staking && mvn install -DskipTests=true 
  STRATEGY_INSTALLATION: cd binance4j-strategy && mvn install -DskipTests=true 
  VISION_INSTALLATION: cd binance4j-vision && mvn install -DskipTests=true 
  WALLET_INSTALLATION: cd binance4j-wallet && mvn install -DskipTests=true 
  WEBSOCKET_INSTALLATION: cd binance4j-websocket && mvn install -DskipTests=true 

jobs:
  
  ##### DEPLOYMENTS #####

  deploy-doc:
      name: Deploy doc

      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: ${{ env.FETCH_DEPTH }}
        - name : Setup Node
          uses: actions/setup-node@v3
          with:
            node-version: 16.x
            cache: yarn
            cache-dependency-path: "./binance4j-documentation/yarn.lock"
            
      - name: Install Docusaurus dependencies
          run: cd binance4j-documentation && yarn install --frozen-lockfile

        - name: Build Docusaurus documentation
          run: cd binance4j-documentation && yarn build

        # COPY doc IN DIR
        - name: Create doc dir
          run: "mkdir doc"

        - name: Copy docusaurus documentation
          run: "cp -R binance4j-documentation/build doc/binance4j-documentation"

        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: doc
            user_name: github-actions[bot]
            user_email: 41898282+github-actions[bot]@users.noreply.github.com