name: deploy

on:
  push:
    branches: 
     - documentation

env:
  FETCH_DEPTH: 0
  JAVA_VERSION: 17
  JAVA_DISTRIBUTION: 'adopt'
  BINANCE_API_KEY: ${{ secrets.BINANCE_API_KEY }}
  BINANCE_API_SECRET: ${{ secrets.BINANCE_API_SECRET }}
  BINANCE_TESTNET_API_KEY: ${{ secrets.BINANCE_TESTNET_API_KEY }}
  BINANCE_TESTNET_API_SECRET: ${{ secrets.BINANCE_TESTNET_API_SECRET }}
  GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
  PASSPHRASE: ${{ secrets.PASSPHRASE }}
  OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
  OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SERVERS: '[{  "id": "ossrh",  "username": "${{ secrets.OSSRH_USERNAME }}",   "password": "${{ secrets.OSSRH_PASSWORD }}"}]'
  BLVT_INSTALLATION: cd binance4j-blvt && mvn install -DskipTests=true 
  C2C_INSTALLATION: cd binance4j-c2c && mvn install -DskipTests=true 
  CONVERT_INSTALLATION: cd binance4j-convert && mvn install -DskipTests=true 
  CORE_INSTALLATION: cd binance4j-core && mvn install -DskipTests=true 
  FIAT_INSTALLATION: cd binance4j-fiat && mvn install -DskipTests=true 
  LOAN_INSTALLATION: cd binance4j-loan && mvn install -DskipTests=true 
  MARGIN_INSTALLATION: cd binance4j-margin && mvn install -DskipTests=true 
  MARKET_INSTALLATION: cd binance4j-market && mvn install -DskipTests=true 
  MINING_INSTALLATION: cd binance4j-mining && mvn install -DskipTests=true 
  NFT_INSTALLATION: cd binance4j-nft && mvn install -DskipTests=true 
  PAY_INSTALLATION: cd binance4j-pay && mvn install -DskipTests=true 
  PORTFOLIO_MARGIN_INSTALLATION: cd binance4j-portfolio-margin && mvn install -DskipTests=true 
  REBATE_INSTALLATION: cd binance4j-rebate && mvn install -DskipTests=true 
  SAVINGS_INSTALLATION: cd binance4j-savings && mvn install -DskipTests=true 
  SPOT_INSTALLATION: cd binance4j-spot && mvn install -DskipTests=true 
  STAKING_INSTALLATION: cd binance4j-staking && mvn install -DskipTests=true 
  STRATEGY_INSTALLATION: cd binance4j-strategy && mvn install -DskipTests=true 
  VISION_INSTALLATION: cd binance4j-vision && mvn install -DskipTests=true 
  WALLET_INSTALLATION: cd binance4j-wallet && mvn install -DskipTests=true 
  WEBSOCKET_INSTALLATION: cd binance4j-websocket && mvn install -DskipTests=true 

jobs:
  
  ##### DEPLOYMENTS #####

  deploy-doc:
      name: Deploy doc

      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: ${{ env.FETCH_DEPTH }}
        - name : Setup Java
          uses: actions/setup-java@v2
          with:
            java-version: ${{ env.JAVA_VERSION }}
            distribution: ${{ env.JAVA_DISTRIBUTION }}
        - name : Setup Node
          uses: actions/setup-node@v3
          with:
            node-version: 16.x
            cache: yarn
            cache-dependency-path: "./binance4j-documentation/yarn.lock"

        # ARTIFACTS INSTALLATIONS

        - name: Install binance4j-core
          run: ${{ env.CORE_INSTALLATION }}
        
        - name: Install binance4j-blvt
          run: ${{ env.BLVT_INSTALLATION }}
        
        - name: Install binance4j-c2c
          run: ${{ env.C2C_INSTALLATION }}
        
        - name: Install binance4j-convert
          run: ${{ env.CONVERT_INSTALLATION }}

        - name: Install binance4j-fiat
          run: ${{ env.FIAT_INSTALLATION }}

        - name: Install binance4j-loan
          run: ${{ env.LOAN_INSTALLATION }}

        - name: Install binance4j-market
          run: ${{ env.MARKET_INSTALLATION }}

        - name: Install binance4j-mining
          run: ${{ env.MINING_INSTALLATION }}

        - name: Install binance4j-nft
          run: ${{ env.NFT_INSTALLATION }}

        - name: Install binance4j-pay
          run: ${{ env.PAY_INSTALLATION }}

        - name: Install binance4j-portfolio-margin
          run: ${{ env.PORTFOLIO_MARGIN_INSTALLATION }}

        - name: Install binance4j-rebate
          run: ${{ env.REBATE_INSTALLATION }}

        - name: Install binance4j-savings
          run: ${{ env.SAVINGS_INSTALLATION }}

        - name: Install binance4j-spot
          run: ${{ env.SPOT_INSTALLATION }}

        - name: Install binance4j-spot
          run: ${{ env.STAKING_INSTALLATION }}

        - name: Install binance4j-vision
          run: ${{ env.VISION_INSTALLATION }}

        - name: Install binance4j-wallet
          run: ${{ env.WALLET_INSTALLATION }}

        - name: Install binance4j-websocket
          run: ${{ env.WEBSOCKET_INSTALLATION }}

        - name: Install binance4j-strategy
          run: ${{ env.STRATEGY_INSTALLATION }}

        - name: Install Docusaurus dependencies
          run: cd binance4j-documentation && yarn install --frozen-lockfile

        - name: Build Docusaurus documentation
          run: cd binance4j-documentation && yarn build

        # COPY doc IN DIR
        - name: Create doc dir
          run: "mkdir doc"

        - name: Copy binance4j-core javadoc
          run: "cp -R binance4j-core/target/apidocs doc/binance4j-core"

        - name: Copy binance4j-c2c javadoc
          run: "cp -R binance4j-c2c/target/apidocs doc/binance4j-c2c"

        - name: Copy binance4j-blvt javadoc
          run: "cp -R binance4j-blvt/target/apidocs doc/binance4j-blvt"

        - name: Copy binance4j-convert javadoc
          run: "cp -R binance4j-convert/target/apidocs doc/binance4j-convert"

        - name: Copy binance4j-fiat javadoc
          run: "cp -R binance4j-fiat/target/apidocs doc/binance4j-fiat"

        - name: Copy binance4j-loan javadoc
          run: "cp -R binance4j-loan/target/apidocs doc/binance4j-loan"

        - name: Copy binance4j-market javadoc
          run: "cp -R binance4j-market/target/apidocs doc/binance4j-market"

        - name: Copy binance4j-mining javadoc
          run: "cp -R binance4j-mining/target/apidocs doc/binance4j-mining"

        - name: Copy binance4j-nft javadoc
          run: "cp -R binance4j-nft/target/apidocs doc/binance4j-nft"

        - name: Copy binance4j-portfolio-margin javadoc
          run: "cp -R binance4j-pay/target/apidocs doc/binance4j-pay"

        - name: Copy binance4j-pay javadoc
          run: "cp -R binance4j-portfolio-margin/target/apidocs doc/binance4j-portfolio-margin"

        - name: Copy binance4j-savings javadoc
          run: "cp -R binance4j-savings/target/apidocs doc/binance4j-savings"

        - name: Copy binance4j-rebate javadoc
          run: "cp -R binance4j-rebate/target/apidocs doc/binance4j-rebate"

        - name: Copy binance4j-spot javadoc
          run: "cp -R binance4j-spot/target/apidocs doc/binance4j-spot"

        - name: Copy binance4j-staking javadoc
          run: "cp -R binance4j-staking/target/apidocs doc/binance4j-staking"

        - name: Copy binance4j-vision javadoc
          run: "cp -R binance4j-vision/target/apidocs doc/binance4j-vision"

        - name: Copy binance4j-wallet javadoc
          run: "cp -R binance4j-wallet/target/apidocs doc/binance4j-wallet"

        - name: Copy binance4j-websocket javadoc
          run: "cp -R binance4j-websocket/target/apidocs doc/binance4j-websocket"

        - name: Copy binance4j-strategy javadoc
          run: "cp -R binance4j-strategy/target/apidocs doc/binance4j-strategy"

        - name: Copy docusaurus documentation
          run: "cp -R binance4j-documentation/build doc/binance4j-documentation"

        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: doc
            user_name: github-actions[bot]
            user_email: 41898282+github-actions[bot]@users.noreply.github.com