package com.binance4j.margin.param;

import com.binance4j.core.annotation.Param;
import com.binance4j.core.dto.RateLimitType;
import com.binance4j.core.param.Params;
import com.binance4j.margin.client.MarginClient;

/**
 * [MarginClient.cancelOCO] params.
 * 
 * @param symbol            Related symbol.
 * @param orderListId       Either {@code orderListId} or
 *                          {@code listClientOrderId} must be provided.
 * @param listClientOrderId Either {@code orderListId} or
 *                          {@code listClientOrderId} must be provided.
 * @param isIsolated        Is the order isolated?
 * @param newClientOrderId  Used to uniquely identify this cancel. Automatically
 *                          generated by default.
 */
@Param(type = RateLimitType.UID)
data class CancelOCOParams(
String symbol, Long orderListId,
String listClientOrderId, Boolean isIsolated,
String newClientOrderId):Params
{

	/**
	 * Creates an instance of {@link CancelOCOParams}.
	 * 
	 * @param symbol Related symbol.
	 */
	public CancelOCOParams(String symbol) {
		this(symbol, null, null, false, null);
	}

	/**
	 * Creates an instance of {@link CancelOCOParams}.
	 * 
	 * @param symbol      Related symbol.
	 * @param orderListId Order list id.
	 */
	public CancelOCOParams(String symbol, Long orderListId) {
		this(symbol, orderListId, null, false, null);
	}

	/**
	 * Creates an instance of {@link CancelOCOParams}.
	 * 
	 * @param symbol           Related symbol.
	 * @param orderListId      Order list id.
	 * @param newClientOrderId Used to uniquely identify this cancel. Automatically
	 *                         generated by default.
	 */
	public CancelOCOParams(String symbol, Long orderListId, String newClientOrderId) {
		this(symbol, orderListId, null, false, newClientOrderId);
	}

	/**
	 * Creates an instance of {@link CancelOCOParams}.
	 * 
	 * @param symbol           Related symbol.
	 * @param orderListId      Order list id.
	 * @param isIsolated       Is the order isolated?
	 * @param newClientOrderId Used to uniquely identify this cancel. Automatically
	 *                         generated by default.
	 */
	public CancelOCOParams(String symbol, Long orderListId, Boolean isIsolated, String newClientOrderId) {
		this(symbol, orderListId, null, isIsolated, newClientOrderId);
	}

	/**
	 * Creates an instance of {@link CancelOCOParams}.
	 * 
	 * @param symbol            Related symbol.
	 * @param listClientOrderId List client order id.
	 */
	public CancelOCOParams(String symbol, String listClientOrderId) {
		this(symbol, null, listClientOrderId, false, null);
	}

	/**
	 * Creates an instance of {@link CancelOCOParams}.
	 * 
	 * @param symbol            Related symbol.
	 * @param listClientOrderId List client order id.
	 * @param newClientOrderId  Used to uniquely identify this cancel. Automatically
	 *                          generated by default.
	 */
	public CancelOCOParams(String symbol, String listClientOrderId, String newClientOrderId) {
		this(symbol, null, listClientOrderId, false, newClientOrderId);
	}

	/**
	 * Creates an instance of {@link CancelOCOParams}.
	 * 
	 * @param symbol            Related symbol.
	 * @param listClientOrderId List client order id.
	 * @param isIsolated        Is the order isolated?
	 * @param newClientOrderId  Used to uniquely identify this cancel. Automatically
	 *                          generated by default.
	 */
	public CancelOCOParams(String symbol, String listClientOrderId, Boolean isIsolated, String newClientOrderId) {
		this(symbol, null, listClientOrderId, isIsolated, newClientOrderId);
	}
}